apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-data-pvc
  labels:
    app: product-similarity
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

# Made with Bob
